### ISSUE TITLE
Export Settings

### ISSUE THREAD

**Issue by ijaouani** [everfor/UsingDirectiveFormatter#5]
Hi,

I would like to export the settings with my team. Is there a way ?

I tried the export settings functionnality in Visual Studio but it seems extensions settings can't be exported. I also try to figure out where UsingDirectiveFormatter stores his settings data without success. Maybe in registry ?

Even a one shot system will be fine.

I use VS 2017.

Thanks.

**Comment by everfor** [comment]
Hi @ijaouani 

The settings used by this extension are saved to 2 registries:

\HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\\{VERSION}\ApplicationPrivateSettings\UsingDirectiveFormatter\Commands\FormatOptionGrid

\HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\\{VERSION}\UsingDirectiveFormatterVSIX

If you export the keys in both registries and apply them to another machine, the settings should be copied over. Replace the {VERSION} with the version of your Visual Studio and you should be good to go (in your case, {VERSION} should be 15.0 for vs 2017).

This has been working for me, but please be extra cautious when doing this, since editing registries can be dangerous.

**Comment by ijaouani** [comment]
Thanks but I can't find it :

![image](https://user-images.githubusercontent.com/27200712/30685344-e4aa9df0-9eb4-11e7-873f-76e97bc039fb.png)

I also try in other vs settings and even in the entire registry with UsingDirectiveFormatter => Nothing found.

**Comment by everfor** [comment]
Hi,

It looks like starting from Visual Studio 2017, the private registry keys are stored in local app data now. Please refer to this link and see if you could create some script to migrate the settings: https://stackoverflow.com/questions/41119996/where-does-visual-studio-2017-rc-store-its-config

**Comment by ijaouani** [comment]
Thanks it works !
